name: tf-exp
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.8
  - tensorflow=2.5.*
  - pip:
    - ipywidgets
    - jupyterlab
    - keras-lmu
    - tensorflow_model_optimization==0.5.*
